### ISSUE TITLE
Handle rar archives

### ISSUE THREAD

**Issue by onc** [manly-man/moodle-destroyer-tools#6]
It seems like pyhon does not provide handling of rar-files without external libraries like this one.

https://pypi.python.org/pypi/unrar/

My question is: should we add external libraries or should we use system-calls?

**Comment by halbtuerke** [comment]
The library you linked to requires another dependency (UnRAR library) to be installed manually. In my opinion there's no point in using this library rather than a “system-call” as the user has to either install the mentioned library or the `rar` application.

I think it's fair to assume that people who want to deal with rar archives have the rar application installed.

**Comment by deubzerm** [comment]
i would go for a "sys-call"

**Comment by onc** [comment]
im sorry for the term: sys-call :laughing: 

ok, so we use `rar`.

**Comment by amkay** [comment]
+1

**Comment by onc** [comment]
I'm closing this issue for now. -1 maintains this project now and handling assignments isn't a goal any more... we may open this issue again in the future, when all key features are done.
